# values.yaml

invoker:
  containerFactory:
    impl: kubernetes
  # This sets the RAM for the Invoker Pod itself
  resources:
    requests:
      memory: "2Gi"
      cpu: "0.5"
    limits:
      memory: "5Gi" 
      cpu: "1.5"
  # This sets the 'budget' the Invoker can spend on actions
  containerPool:
    userMemory: "4096m"

k8s:
  persistence:
    enabled: false

nginx:
  httpsNodePort: 31001

scheduler:
  enabled: false

whisk:
  ingress:
    apiHostName: 10.10.1.1
    apiHostPort: 31001
    type: NodePort
  # THIS IS THE CRITICAL ADDITION
  limits:
    actions:
      memory:
        max: "2048m"   # Allows the Controller to accept 2GB actions
        min: "128m"
        std: "256m"